/* src/config_flopcpp.h.  Generated by configure.  */
/* src/config_flopcpp.h.in. */

/* Version number of project */
#define FLOPCPP_VERSION "1.1.1"

/* Major Version number of project */
#define FLOPCPP_VERSION_MAJOR 1

/* Minor Version number of project */
#define FLOPCPP_VERSION_MINOR 1

/* Release Version number of project */
#define FLOPCPP_VERSION_RELEASE 1
